-- Run this in Supabase SQL Editor to add comments support to an existing database.

-- Ensure the comments table exists before applying policies and grants.
create table if not exists public.comments (
  id int generated by default as identity primary key,
  species_id int not null references public.species (id) on delete cascade,
  author uuid not null references public.profiles (id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default now()
);

-- Turn on row-level security so policy rules below are enforced.
alter table public.comments
  enable row level security;

-- Idempotently create policies (safe to run multiple times).
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'comments'
      and policyname = 'Comments are viewable by everyone.'
  ) then
    create policy "Comments are viewable by everyone." on public.comments
      for select using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'comments'
      and policyname = 'Users can insert their own comments.'
  ) then
    create policy "Users can insert their own comments." on public.comments
      for insert with check (auth.uid() = author);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'comments'
      and policyname = 'Users can delete their own comments.'
  ) then
    create policy "Users can delete their own comments." on public.comments
      for delete using (auth.uid() = author);
  end if;
end $$;

-- Speeds up sorted comment reads per species card.
create index if not exists comments_species_id_created_at_idx
  on public.comments (species_id, created_at desc);

-- Grant table/sequence access to anonymous + authenticated Supabase roles.
grant select, insert, update, delete on table public.comments to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
