-- PostgreSQL tutorial: https://supabase.com/docs/guides/database/tables#resources

-- -----------------------------------------------------------------------------
-- 1) Profiles table + policies
-- -----------------------------------------------------------------------------
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text unique not null,
  display_name text not null,
  biography text
);
-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
create function public.handle_new_user()
returns trigger as $$
declare username text;
begin
  select substring(new.email from '(.*)@') into username;
  insert into public.profiles (id, email, display_name, biography)
  values (new.id, new.email, username, null);
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- -----------------------------------------------------------------------------
-- 2) Shared enums used by species rows
-- -----------------------------------------------------------------------------
create type kingdom as enum ('Animalia', 'Plantae', 'Fungi', 'Protista', 'Archaea', 'Bacteria');
create type endangerment_status as enum (
  'Not Evaluated',
  'Data Deficient',
  'Least Concern',
  'Near Threatened',
  'Vulnerable',
  'Endangered',
  'Critically Endangered',
  'Extinct in the Wild',
  'Extinct'
);

-- -----------------------------------------------------------------------------
-- 3) Species table + policies
-- -----------------------------------------------------------------------------
-- Create a table for species
create table species (
  id int generated by default as identity primary key,
  scientific_name text unique not null,
  common_name text,
  total_population int,
  kingdom kingdom not null,
  endangerment_status endangerment_status not null default 'Not Evaluated',
  description text,
  image text,
  author uuid not null references profiles
);
-- Set up Row Level Security (RLS)
alter table species
  enable row level security;

create policy "Species are viewable by everyone." on species
  for select using (true);

create policy "Users can insert their own species." on species
  for insert with check (auth.uid() = author);

create policy "Users can update their created species." on species
  for update using (auth.uid() = author);

create policy "Users can delete their created species." on species
  for delete using (auth.uid() = author);

-- -----------------------------------------------------------------------------
-- 4) Comments table + policies
-- -----------------------------------------------------------------------------
-- Create a table for species comments
create table comments (
  id int generated by default as identity primary key,
  species_id int not null references species (id) on delete cascade,
  author uuid not null references profiles (id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default now()
);
-- Set up Row Level Security (RLS)
alter table comments
  enable row level security;

create policy "Comments are viewable by everyone." on comments
  for select using (true);

create policy "Users can insert their own comments." on comments
  for insert with check (auth.uid() = author);

create policy "Users can delete their own comments." on comments
  for delete using (auth.uid() = author);

create index comments_species_id_created_at_idx
  on comments (species_id, created_at desc);

-- -----------------------------------------------------------------------------
-- 5) Species bookmarks table + policies
-- -----------------------------------------------------------------------------
-- Per-user saved species rows (unique per user/species pair).
create table species_bookmarks (
  user_id uuid not null references profiles (id) on delete cascade,
  species_id int not null references species (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, species_id)
);
-- Set up Row Level Security (RLS)
alter table species_bookmarks
  enable row level security;

create policy "Users can view their own bookmarks." on species_bookmarks
  for select using (auth.uid() = user_id);

create policy "Users can insert their own bookmarks." on species_bookmarks
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own bookmarks." on species_bookmarks
  for delete using (auth.uid() = user_id);

create index species_bookmarks_user_id_created_at_idx
  on species_bookmarks (user_id, created_at desc);

-- -----------------------------------------------------------------------------
-- 6) Grants for Supabase client roles
-- -----------------------------------------------------------------------------
-- Grant table access to Supabase client roles.
-- RLS still applies, these grants only allow the roles to reach the tables.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.profiles to anon, authenticated;
grant select, insert, update, delete on table public.species to anon, authenticated;
grant select, insert, update, delete on table public.comments to anon, authenticated;
grant select, insert, delete on table public.species_bookmarks to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 7) Trigger to keep species author immutable after insert
-- -----------------------------------------------------------------------------
-- Prevent the author field of a created species from being changed
create function public.species_columns_updateable()
returns trigger as $$
begin
  if new.author <> old.author then
    raise exception 'changing species author is not allowed';
  end if;
  return new;
end;
$$ language plpgsql security definer;
create trigger columns_updateable
  before update on public.species
  for each row execute procedure public.species_columns_updateable();
